[[redirects]]
  from = "/board"
  to = "http://mytest.cafe24app.com/board"
  status = 200
  force = true

[[redirects]]
  from = "/board/2"
  to = "http://mytest.cafe24app.com/board/2"
  status = 200
  force = true
